# Generated by Django 5.2.7 on 2026-03-13 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='系所代碼')),
                ('name_zh', models.CharField(max_length=50, verbose_name='系所名稱')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='學制代碼')),
                ('name_zh', models.CharField(max_length=50, verbose_name='學制名稱')),
            ],
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='班級代碼')),
                ('name_zh', models.CharField(max_length=50, verbose_name='班級名稱')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department', verbose_name='所屬系所')),
            ],
        ),
    ]
