# Generated by Django 5.2.7 on 2026-03-14 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgroup',
            options={'verbose_name': '班級群組', 'verbose_name_plural': '3. 班級群組'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '系所', 'verbose_name_plural': '2. 系所'},
        ),
        migrations.AlterModelOptions(
            name='programtype',
            options={'verbose_name': '學制', 'verbose_name_plural': '1. 學制'},
        ),
        migrations.AddField(
            model_name='department',
            name='program_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.programtype', verbose_name='所屬學制'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='班級代碼'),
        ),
    ]
