# Generated by Django 5.2.7 on 2026-03-20 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fill_department_campus_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='core.campus', verbose_name='校區'),
        ),
    ]
