# Generated by Django 5.2.7 on 2026-03-13 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_academic_year', models.IntegerField(verbose_name='開課學年')),
                ('origin_term', models.IntegerField(verbose_name='開課學期')),
                ('used_price', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='二手價')),
                ('condition_level', models.CharField(choices=[('NEW', '全新'), ('GOOD', '良好'), ('FAIR', '普通'), ('POOR', '較差')], max_length=10, verbose_name='書況')),
                ('description', models.TextField(blank=True, null=True, verbose_name='商品說明')),
                ('seller_note', models.TextField(blank=True, null=True, verbose_name='賣家備註')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '審核中'), ('PUBLISHED', '已上架'), ('RESERVED', '已保留'), ('SOLD', '已售出'), ('OFF_SHELF', '已下架')], default='DRAFT', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間(軟刪除)')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='books.book')),
                ('origin_class_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classgroup')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.URLField(verbose_name='圖片連結或路徑')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否為封面')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_images', to='listings.listing')),
            ],
        ),
    ]
