# Generated by Django 5.2.7 on 2026-03-17 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('core', '0002_alter_classgroup_options_alter_department_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_academic_year', models.PositiveSmallIntegerField(verbose_name='原始學年度')),
                ('origin_term', models.PositiveSmallIntegerField(choices=[(1, '上學期'), (2, '下學期')], verbose_name='原始學期')),
                ('used_price', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='二手售價')),
                ('condition_level', models.CharField(choices=[('NEW', '全新'), ('GOOD', '良好'), ('FAIR', '普通'), ('POOR', '較差')], max_length=10, verbose_name='書況等級')),
                ('description', models.TextField(blank=True, verbose_name='商品說明')),
                ('seller_note', models.TextField(blank=True, verbose_name='賣家備註')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '審核中'), ('PUBLISHED', '上架中'), ('RESERVED', '已保留'), ('SOLD', '已售出'), ('OFF_SHELF', '已下架')], default='DRAFT', max_length=20, verbose_name='刊登狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除(下架)時間')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='books.book', verbose_name='書籍')),
                ('origin_class_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classgroup', verbose_name='原始課程班級')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='賣家')),
            ],
            options={
                'verbose_name': '二手書刊登',
                'verbose_name_plural': '1. 二手書刊登',
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.ImageField(upload_to='listings/%Y/%m/', verbose_name='圖片')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否為主圖')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_images', to='listings.listing', verbose_name='所屬刊登')),
            ],
            options={
                'verbose_name': '刊登圖片',
                'verbose_name_plural': '2. 刊登圖片',
                'ordering': ['sort_order', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='BookFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏時間')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='書籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '書籍收藏',
                'verbose_name_plural': '3. 書籍收藏',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
