# Generated by Django 5.2.7 on 2026-03-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_add_profile_fields'),
        ('core', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_academic_year', models.PositiveSmallIntegerField(verbose_name='原使用學年')),
                ('origin_term', models.PositiveSmallIntegerField(verbose_name='原使用學期')),
                ('used_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='二手價')),
                ('condition_level', models.CharField(choices=[('LIKE_NEW', '幾全新'), ('GOOD', '良好'), ('FAIR', '普通'), ('POOR', '差')], default='GOOD', max_length=20, verbose_name='書況等級')),
                ('description', models.TextField(blank=True, null=True, verbose_name='商品描述')),
                ('seller_note', models.TextField(blank=True, null=True, verbose_name='賣家備註')),
                ('status', models.CharField(choices=[('AVAILABLE', '可購買'), ('RESERVED', '已保留'), ('SOLD', '已售出'), ('OFF_SHELF', '已下架'), ('REMOVED', '已移除'), ('DELETED', '已刪除')], default='AVAILABLE', max_length=20, verbose_name='刊登狀態')),
                ('off_shelf_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='下架原因')),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='驗證風險分數')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='軟刪除時間')),
                ('reserved_at', models.DateTimeField(blank=True, null=True, verbose_name='保留時間')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='售出時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='books.book', verbose_name='書籍')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_listings', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('origin_class_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='origin_listings', to='core.classgroup', verbose_name='原使用班級')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='賣家')),
            ],
            options={
                'verbose_name': '刊登',
                'verbose_name_plural': '刊登',
                'db_table': 'listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, verbose_name='檔案路徑')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序值')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否為首圖')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing', verbose_name='刊登')),
            ],
            options={
                'verbose_name': '刊登圖片',
                'verbose_name_plural': '刊登圖片',
                'db_table': 'listing_images',
                'ordering': ['listing', 'sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['seller', 'status', 'created_at'], name='listings_seller_status_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['book', 'status', 'created_at'], name='listings_book_status_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'created_at'], name='listings_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['origin_class_group', 'origin_academic_year', 'origin_term'], name='listings_origin_cohort_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['deleted_at'], name='listings_deleted_at_idx'),
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['listing', 'sort_order'], name='listing_img_listing_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['listing', 'is_primary'], name='listing_img_listing_primary_idx'),
        ),
    ]
