# Generated by Django 5.2.7 on 2026-03-18
# listings.0002: 補上 Listing.accepted_request FK
# 此 migration 依賴 purchase_requests.0001_initial（PurchaseRequest 存在後才可建立 FK）

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('purchase_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='accepted_request',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='accepted_listing',
                to='purchase_requests.purchaserequest',
                verbose_name='已接受請求'
            ),
        ),
    ]
