# Generated by Django 5.2.7 on 2026-03-14 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_alter_bookapplicability_options_and_more'),
        ('core', '0002_alter_classgroup_options_alter_department_options_and_more'),
        ('listings', '0002_purchaserequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookfavorite',
            options={'verbose_name': '書籍收藏', 'verbose_name_plural': '4. 書籍收藏'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': '二手書刊登', 'verbose_name_plural': '1. 二手書刊登'},
        ),
        migrations.AlterModelOptions(
            name='listingimage',
            options={'ordering': ['sort_order', '-is_primary'], 'verbose_name': '刊登圖片', 'verbose_name_plural': '2. 刊登圖片'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'verbose_name': '預約請求', 'verbose_name_plural': '3. 預約請求'},
        ),
        migrations.AlterUniqueTogether(
            name='bookfavorite',
            unique_together={('user', 'book')},
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='message',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='buyer_message',
            field=models.TextField(blank=True, verbose_name='買家留言'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='過期時間'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='回應時間'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='risk_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='風險分數'),
        ),
        migrations.AlterField(
            model_name='bookfavorite',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='書籍'),
        ),
        migrations.AlterField(
            model_name='bookfavorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='收藏時間'),
        ),
        migrations.AlterField(
            model_name='bookfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='books.book', verbose_name='書籍'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition_level',
            field=models.CharField(choices=[('NEW', '全新'), ('GOOD', '良好'), ('FAIR', '普通'), ('POOR', '較差')], max_length=10, verbose_name='書況等級'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='刪除(下架)時間'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, default=1, verbose_name='商品說明'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='origin_academic_year',
            field=models.PositiveSmallIntegerField(verbose_name='原始學年度'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='origin_class_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classgroup', verbose_name='原始課程班級'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='origin_term',
            field=models.PositiveSmallIntegerField(choices=[(1, '上學期'), (2, '下學期')], verbose_name='原始學期'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='賣家'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seller_note',
            field=models.TextField(blank=True, default=1, verbose_name='賣家備註'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '審核中'), ('PUBLISHED', '上架中'), ('RESERVED', '已保留'), ('SOLD', '已售出'), ('OFF_SHELF', '已下架')], default='DRAFT', max_length=20, verbose_name='刊登狀態'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='used_price',
            field=models.DecimalField(decimal_places=0, max_digits=8, verbose_name='二手售價'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='file_path',
            field=models.ImageField(upload_to='listings/%Y/%m/', verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='是否為主圖'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_images', to='listings.listing', verbose_name='所屬刊登'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('PENDING', '待處理'), ('ACCEPTED', '已接受'), ('REJECTED', '已拒絕'), ('CANCELLED_BY_BUYER', '買家取消'), ('CANCELLED_BY_SELLER', '賣家取消'), ('EXPIRED', '已過期')], default='PENDING', max_length=20, verbose_name='請求狀態'),
        ),
        migrations.RemoveField(
            model_name='bookfavorite',
            name='listing',
        ),
    ]
