# Generated by Django 5.2.7 on 2026-03-13 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='書名')),
                ('author_display', models.CharField(max_length=255, verbose_name='作者')),
                ('isbn13', models.CharField(max_length=13, unique=True, verbose_name='ISBN-13')),
                ('isbn10', models.CharField(blank=True, max_length=10, null=True, verbose_name='ISBN-10')),
                ('publisher', models.CharField(max_length=100, verbose_name='出版社')),
                ('publication_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='出版日期')),
                ('edition', models.CharField(blank=True, max_length=50, null=True, verbose_name='版本')),
                ('cover_image_url', models.URLField(blank=True, null=True, verbose_name='封面圖片連結')),
            ],
        ),
        migrations.CreateModel(
            name='BookApplicability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='課程名稱')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicabilities', to='books.book', verbose_name='書籍')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department', verbose_name='適用系所')),
            ],
        ),
    ]
