# Generated by Django 5.2.7 on 2026-03-14 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('core', '0002_alter_classgroup_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '書籍庫', 'verbose_name_plural': '1. 書籍庫'},
        ),
        migrations.AlterModelOptions(
            name='bookapplicability',
            options={'verbose_name': '適用課程', 'verbose_name_plural': '2. 適用課程'},
        ),
        migrations.RemoveField(
            model_name='bookapplicability',
            name='department',
        ),
        migrations.AddField(
            model_name='bookapplicability',
            name='class_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.classgroup', verbose_name='適用班級'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=255, verbose_name='出版社'),
        ),
    ]
