# Generated by Django 5.2.7 on 2026-03-18 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900, message='請輸入西元年（1900以上）'), django.core.validators.MaxValueValidator(2100)], verbose_name='出版年份'),
        ),
    ]
