# Generated by Django 5.2.7 on 2026-03-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_add_profile_fields'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '等待中'), ('ACCEPTED', '已接受'), ('REJECTED', '已拒絕'), ('CANCELLED_BY_BUYER', '買家取消'), ('CANCELLED_BY_SELLER', '賣家取消'), ('EXPIRED', '已過期')], default='PENDING', max_length=30, verbose_name='請求狀態')),
                ('buyer_message', models.TextField(blank=True, null=True, verbose_name='買家留言')),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='驗證風險分數')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='逾時時間')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='回應時間')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消時間')),
                ('contact_released_at', models.DateTimeField(blank=True, null=True, verbose_name='聯絡資訊開放時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='買家')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='listings.listing', verbose_name='刊登')),
            ],
            options={
                'verbose_name': '預約請求',
                'verbose_name_plural': '預約請求',
                'db_table': 'purchase_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['listing', 'status', 'created_at'], name='pr_listing_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['buyer', 'status', 'created_at'], name='pr_buyer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['expires_at'], name='pr_expires_at_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status', 'created_at'], name='pr_status_created_idx'),
        ),
    ]
