# Generated by Django 5.2.7 on 2026-03-17 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '待處理'), ('ACCEPTED', '已接受 (保留中)'), ('REJECTED', '已拒絕'), ('CANCELLED_BY_BUYER', '買家取消'), ('CANCELLED_BY_SELLER', '賣家取消'), ('COMPLETED', '交易完成'), ('EXPIRED', '已過期')], default='PENDING', max_length=20, verbose_name='請求狀態')),
                ('buyer_message', models.TextField(blank=True, verbose_name='買家留言')),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='風險分數')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='過期時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='回應時間')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL, verbose_name='買家')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='listings.listing', verbose_name='刊登商品')),
            ],
            options={
                'verbose_name': '預約請求',
                'verbose_name_plural': '預約請求管理',
            },
        ),
    ]
