# Generated by Django 5.2.7 on 2026-03-13 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='student_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_status',
            field=models.CharField(choices=[('ACTIVE', '正常'), ('SUSPENDED', '停權'), ('RESTRICTED_LISTING', '限制刊登')], default='ACTIVE', max_length=20, verbose_name='帳號狀態'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50, verbose_name='暱稱')),
                ('student_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='學號')),
                ('grade_no', models.IntegerField(blank=True, null=True, verbose_name='年級')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='聯絡信箱')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='頭像連結')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classgroup')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('program_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.programtype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
