# Generated by Django 5.2.7 on 2026-03-18 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50, verbose_name='顯示名稱')),
                ('student_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='學號')),
                ('grade_no', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年級')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='聯絡信箱')),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='頭像網址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core.classgroup', verbose_name='班級')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core.department', verbose_name='系所')),
                ('program_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core.programtype', verbose_name='學制')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者個人檔',
                'verbose_name_plural': '使用者個人檔',
                'db_table': 'user_profiles',
                'indexes': [models.Index(fields=['program_type', 'department', 'class_group'], name='user_profiles_prog_dept_idx')],
            },
        ),
    ]
