# Generated by Django 5.2.7 on 2026-03-14 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_department_and_more'),
        ('core', '0002_alter_classgroup_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '使用者帳號', 'verbose_name_plural': '1. 使用者帳號'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '使用者資料', 'verbose_name_plural': '2. 使用者資料'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_status',
            field=models.CharField(choices=[('ACTIVE', '啟用'), ('SUSPENDED', '停權'), ('RESTRICTED_LISTING', '限制刊登')], default='ACTIVE', max_length=20, verbose_name='帳號狀態'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classgroup', verbose_name='班級'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department', verbose_name='系所'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(max_length=50, verbose_name='顯示暱稱'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade_no',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1年級'), (2, '2年級'), (3, '3年級'), (4, '4年級'), (5, '5年級')], null=True, verbose_name='年級'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='program_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.programtype', verbose_name='學制'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='關聯帳號'),
        ),
    ]
