# Generated by Django 5.2.7 on 2026-03-18
# 第一階段 migration：users_user 補齊（過渡版本）

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        # ===== 第一階段：新增欄位（皆可為空/有預設值）=====

        # google_sub: 第一階段設為 nullable + unique（尚未設 not null，等第二階段）
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name='Google 主體識別碼'
            ),
        ),

        # auth_provider: 有 default='GOOGLE'，不會失敗
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(
                default='GOOGLE',
                max_length=20,
                verbose_name='驗證來源'
            ),
        ),

        # account_status: 有 default='ACTIVE'，不會失敗
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(
                choices=[
                    ('ACTIVE', '正常'),
                    ('SUSPENDED', '停權'),
                    ('RESTRICTED_LISTING', '限制刊登')
                ],
                default='ACTIVE',
                max_length=20,
                verbose_name='帳號狀態'
            ),
        ),

        # account_status_reason: nullable，不會失敗
        migrations.AddField(
            model_name='user',
            name='account_status_reason',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name='狀態原因'
            ),
        ),

        # created_at: auto_now_add=True，現有資料會自動填入目前時間
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name='建立時間'
            ),
            preserve_default=False,
        ),

        # updated_at: auto_now=True，現有資料會自動填入目前時間
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                verbose_name='更新時間'
            ),
        ),

        # ===== 第一階段：新增索引 =====        
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['account_status'],
                name='users_user_status_idx'
            ),
        ),

        # ===== 注意：以下項目延後到第二階段處理 =====
        # - email unique（需先檢查資料是否有重複）
        # - google_sub not null（需先確認所有使用者都有 google_sub）
    ]
