# Generated by Django 5.2.7 on 2026-03-18
# accounts.0004: 將 User.email 的 migration model state 與 Python model state 同步
# 兩者皆為 EmailField(max_length=254, blank=True)，本支 migration 為 explicit state reconciliation
# 第一階段策略：email 保持 non-unique，blank=True，null=False（沿用 AbstractUser 預設）
# 第二階段（0005 以後）再加入 unique=True

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_add_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                blank=True,
                max_length=254,
                verbose_name='校內信箱'
            ),
        ),
    ]
