# Generated by Django 5.2.7 on 2026-03-13 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('listing', '刊登'), ('user', '使用者')], max_length=20, verbose_name='目標類型')),
                ('target_listing_id', models.IntegerField(blank=True, null=True, verbose_name='目標刊登ID')),
                ('target_user_id', models.IntegerField(blank=True, null=True, verbose_name='目標使用者ID')),
                ('reason_code', models.CharField(max_length=50, verbose_name='檢舉原因代碼')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='詳細說明')),
                ('status', models.CharField(choices=[('OPEN', '未處理'), ('IN_REVIEW', '審核中'), ('RESOLVED', '已解決'), ('DISMISSED', '已駁回')], default='OPEN', max_length=20, verbose_name='狀態')),
                ('resolution_note', models.TextField(blank=True, null=True, verbose_name='處理備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='處置動作')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='reports.report')),
            ],
        ),
    ]
