# Generated by Django 5.2.7 on 2026-03-14 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationaction',
            options={'verbose_name': '審核處置紀錄', 'verbose_name_plural': '2. 審核處置紀錄'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': '檢舉紀錄', 'verbose_name_plural': '1. 檢舉紀錄'},
        ),
        migrations.RenameField(
            model_name='moderationaction',
            old_name='action',
            new_name='action_taken',
        ),
        migrations.RemoveField(
            model_name='moderationaction',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='resolution_note',
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='審核人員'),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='resolution_note',
            field=models.TextField(blank=True, verbose_name='處理備註'),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='處理時間'),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='reports.report', verbose_name='關聯檢舉'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='report',
            name='detail',
            field=models.TextField(blank=True, default=1, verbose_name='補充說明'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='reason_code',
            field=models.CharField(max_length=50, verbose_name='檢舉原因'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL, verbose_name='檢舉人'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('OPEN', '未處理'), ('IN_REVIEW', '審核中'), ('RESOLVED', '已解決'), ('DISMISSED', '已撤銷')], default='OPEN', max_length=20, verbose_name='處理狀態'),
        ),
    ]
