# Generated by Django 5.2.7 on 2026-03-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_add_profile_fields'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('LISTING', '刊登'), ('USER', '使用者')], max_length=20, verbose_name='檢舉目標類型')),
                ('reason_code', models.CharField(choices=[('SPAM', '垃圾訊息'), ('SCAM', '詐騙'), ('INFRINGEMENT', '侵權'), ('NOT_TEXTBOOK', '非教科書'), ('INAPPROPRIATE', '不當內容')], max_length=50, verbose_name='檢舉原因')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='說明')),
                ('status', models.CharField(choices=[('OPEN', '待處理'), ('IN_REVIEW', '審查中'), ('RESOLVED', '已處理'), ('DISMISSED', '已駁回')], default='OPEN', max_length=20, verbose_name='檢舉狀態')),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='風險分數')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='處理時間')),
                ('resolution_note', models.TextField(blank=True, null=True, verbose_name='處理說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_handled', to=settings.AUTH_USER_MODEL, verbose_name='處理人')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL, verbose_name='檢舉人')),
                ('target_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='listings.listing', verbose_name='目標刊登')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_against', to=settings.AUTH_USER_MODEL, verbose_name='目標使用者')),
            ],
            options={
                'verbose_name': '檢舉',
                'verbose_name_plural': '檢舉',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('WARN_USER', '警告'), ('SUSPEND_USER', '停權'), ('UNSUSPEND_USER', '解除停權'), ('REMOVE_LISTING', '移除刊登'), ('REQUEST_EDIT', '要求修正')], max_length=50, verbose_name='處置類型')),
                ('reason', models.TextField(verbose_name='原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='管理員')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='moderation.report', verbose_name='關聯檢舉')),
                ('target_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='listings.listing', verbose_name='目標刊登')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_against', to=settings.AUTH_USER_MODEL, verbose_name='目標使用者')),
            ],
            options={
                'verbose_name': '管理處置',
                'verbose_name_plural': '管理處置',
                'db_table': 'moderation_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['target_type', 'status', 'created_at'], name='reports_target_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['target_listing', 'status'], name='reports_target_listing_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['target_user', 'status'], name='reports_target_user_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter', 'created_at'], name='reports_reporter_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['admin', 'action_type', 'created_at'], name='mod_admin_action_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['target_user', 'created_at'], name='mod_target_user_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['target_listing', 'created_at'], name='mod_target_listing_idx'),
        ),
    ]
