# Generated by Django 5.2.7 on 2026-03-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_add_profile_fields'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn13', models.CharField(max_length=20, unique=True, verbose_name='ISBN-13')),
                ('isbn10', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN-10')),
                ('title', models.CharField(max_length=255, verbose_name='書名')),
                ('author_display', models.CharField(max_length=255, verbose_name='作者')),
                ('publisher', models.CharField(max_length=255, verbose_name='出版社')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='出版日期')),
                ('publication_date_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='出版日期原始字串')),
                ('edition', models.CharField(blank=True, max_length=50, null=True, verbose_name='版次')),
                ('language_code', models.CharField(default='zh-TW', max_length=20, verbose_name='語言代碼')),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='封面圖片')),
                ('metadata_source', models.CharField(choices=[('GOOGLE_BOOKS', 'Google Books'), ('MANUAL', '手動輸入'), ('LOCAL', '本地資料')], default='MANUAL', max_length=30, verbose_name='書目資料來源')),
                ('metadata_status', models.CharField(choices=[('AUTO_IMPORTED', '自動匯入'), ('MANUALLY_CONFIRMED', '已手動確認'), ('NEEDS_REVIEW', '需審核')], default='NEEDS_REVIEW', max_length=30, verbose_name='書目狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '書籍',
                'verbose_name_plural': '書籍',
                'db_table': 'books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookApplicability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveSmallIntegerField(verbose_name='學年')),
                ('term', models.PositiveSmallIntegerField(verbose_name='學期')),
                ('source_type', models.CharField(choices=[('FROM_LISTING', '來自刊登'), ('ADMIN_CURATED', '管理員精選')], default='ADMIN_CURATED', max_length=20, verbose_name='來源類型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicabilities', to='books.book', verbose_name='書籍')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_applicabilities', to='core.classgroup', verbose_name='班級')),
            ],
            options={
                'verbose_name': '書籍適用對象',
                'verbose_name_plural': '書籍適用對象',
                'db_table': 'book_applicabilities',
                'ordering': ['book', 'academic_year', 'term'],
            },
        ),
        migrations.CreateModel(
            name='BookFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='books.book', verbose_name='書籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_favorites', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '書籍收藏',
                'verbose_name_plural': '書籍收藏',
                'db_table': 'book_favorites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn10'], name='books_isbn10_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='books_title_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author_display'], name='books_author_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publisher'], name='books_publisher_idx'),
        ),
        migrations.AddIndex(
            model_name='bookapplicability',
            index=models.Index(fields=['class_group', 'academic_year', 'term'], name='book_app_class_yr_term_idx'),
        ),
        migrations.AddIndex(
            model_name='bookapplicability',
            index=models.Index(fields=['book', 'academic_year', 'term'], name='book_app_book_yr_term_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookapplicability',
            unique_together={('book', 'academic_year', 'term', 'class_group')},
        ),
        migrations.AddIndex(
            model_name='bookfavorite',
            index=models.Index(fields=['book', 'created_at'], name='book_fav_book_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookfavorite',
            unique_together={('user', 'book')},
        ),
    ]
