# Generated by Django 5.2.7 on 2026-03-18
# books.0002: 補上 BookApplicability.source_listing FK
# 此 migration 依賴 listings.0001_initial（Listing 存在後才可建立 FK）

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookapplicability',
            name='source_listing',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='applicabilities',
                to='listings.listing',
                verbose_name='來源刊登'
            ),
        ),
    ]
