# Generated by Django 5.2.7 on 2026-03-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_schema_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='metadata_source',
            field=models.CharField(choices=[('MANUAL', '手動輸入'), ('MYTB', 'Mytb API 匯入'), ('IMPORT', '批量匯入')], default='MANUAL', max_length=30, verbose_name='書目資料來源'),
        ),
        migrations.AlterField(
            model_name='book',
            name='metadata_status',
            field=models.CharField(choices=[('NEEDS_REVIEW', '待審核'), ('MANUALLY_CONFIRMED', '已確認')], default='NEEDS_REVIEW', max_length=30, verbose_name='書目狀態'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date_text',
            field=models.CharField(blank=True, help_text='外部來源原始日期快照，不可編輯', max_length=50, null=True, verbose_name='出版日期原始字串'),
        ),
    ]
