# Generated by Django 5.2.7 on 2026-03-25 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_reject_reason_alter_listing_status'),
    ]

    operations = [
    ]
