# Generated by Django 5.2.7 on 2026-03-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_reject_reason_alter_listing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingimage',
            name='file_path',
        ),
        migrations.AddField(
            model_name='listing',
            name='target_audience',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='適用人群/目標受眾'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='file_name',
            field=models.CharField(default='', max_length=255, verbose_name='原檔案名稱'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_binary',
            field=models.BinaryField(default=b'', verbose_name='圖片二進制數據'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='mime_type',
            field=models.CharField(default='image/jpeg', max_length=50, verbose_name='MIME 類型'),
        ),
    ]
