# Generated by Django 5.2.7 on 2026-03-18 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='學制代碼')),
                ('name_zh', models.CharField(max_length=100, verbose_name='中文名稱')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='英文名稱')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '學制',
                'verbose_name_plural': '學制',
                'db_table': 'program_types',
                'ordering': ['sort_order', 'code'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='program_types_active_sort_idx')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='系所代碼')),
                ('name_zh', models.CharField(max_length=100, verbose_name='中文名稱')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='英文名稱')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.programtype', verbose_name='學制')),
            ],
            options={
                'verbose_name': '系所',
                'verbose_name_plural': '系所',
                'db_table': 'departments',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='班級代碼')),
                ('name_zh', models.CharField(max_length=100, verbose_name='班級名稱')),
                ('grade_no', models.PositiveSmallIntegerField(verbose_name='年級')),
                ('section_code', models.CharField(max_length=5, verbose_name='班別代碼')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='core.department', verbose_name='系所')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='core.programtype', verbose_name='學制')),
            ],
            options={
                'verbose_name': '班級',
                'verbose_name_plural': '班級',
                'db_table': 'class_groups',
                'ordering': ['code'],
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['program_type', 'name_zh'], name='dept_prog_name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('program_type', 'code')},
        ),
        migrations.AddIndex(
            model_name='classgroup',
            index=models.Index(fields=['program_type', 'department', 'grade_no'], name='class_prog_dept_grade_idx'),
        ),
        migrations.AddIndex(
            model_name='classgroup',
            index=models.Index(fields=['department', 'grade_no', 'section_code'], name='class_dept_grade_sect_idx'),
        ),
    ]
