# Generated by Django 5.2.7 on 2026-03-21 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='校區代碼')),
                ('name_zh', models.CharField(max_length=100, verbose_name='中文名稱')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='英文名稱')),
                ('short_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='簡稱')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '校區',
                'verbose_name_plural': '校區',
                'db_table': 'campuses',
                'ordering': ['sort_order', 'code'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='campuses_active_sort_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentNumberRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_year_digits', models.PositiveSmallIntegerField(default=3, verbose_name='入學年位數')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='說明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_number_rules', to='core.department', verbose_name='系所')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_number_rules', to='core.programtype', verbose_name='學制')),
            ],
            options={
                'verbose_name': '學號規則',
                'verbose_name_plural': '學號規則',
                'db_table': 'student_number_rules',
                'ordering': ['program_type__sort_order', 'department__code'],
                'indexes': [models.Index(fields=['program_type', 'department'], name='snr_prog_dept_idx')],
                'unique_together': {('program_type', 'department')},
            },
        ),
    ]
