# Generated by Django 5.2.7 on 2026-03-21 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_campus'),
    ]

    operations = [
        # 刪除沒有 campus 的 Department 記錄
        migrations.RunSQL(
            "DELETE FROM departments WHERE campus_id IS NULL",
            "-- Reverse: No action needed"
        ),
        # 修改 campus 欄位允許 NULL
        migrations.AlterField(
            model_name='department',
            name='campus',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='departments',
                to='core.campus',
                verbose_name='校區'
            ),
        ),
    ]
