# Generated by Django 5.2.7 on 2026-03-13 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=50, verbose_name='通知類型')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('message', models.TextField(verbose_name='訊息內容')),
                ('related_listing_id', models.IntegerField(blank=True, null=True, verbose_name='相關刊登ID')),
                ('related_request_id', models.IntegerField(blank=True, null=True, verbose_name='相關請求ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已讀')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='讀取時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
