# Generated by Django 5.2.7 on 2026-03-14 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '通知紀錄', 'verbose_name_plural': '通知紀錄'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_at',
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='已讀狀態'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_listing_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='關聯刊登ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_request_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='關聯請求ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收者'),
        ),
    ]
