name: Django CI/CD Deploy

on:
  push:
    branches: 
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to GCP VM and Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.GCP_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          port: 22
          debug: true
          script_stop: true
          script: |
            whoami
            echo $HOME
            hostname
      
            if [ "${{ github.ref_name }}" = "main" ]; then
              TARGET_DIR="/var/www/ntubook"
            elif [ "${{ github.ref_name }}" = "dev" ]; then
              TARGET_DIR="/var/www/ntubook_dev"
            else
              echo "Unsupported branch: ${{ github.ref_name }}"
              exit 1
            fi
      
            echo "準備部署分支: ${{ github.ref_name }} 到路徑: $TARGET_DIR"
            cd "$TARGET_DIR"
      
            git fetch origin "${{ github.ref_name }}"
            git reset --hard "origin/${{ github.ref_name }}"
      
            touch ntub_usedbooks/wsgi.py
            echo "部署完成！"
            
            echo "部署完成！"
